name = input("Enter Your Name : ")
surname = input("Enter Your Surname : ")
country_born = input("Where were you born? : ")
age = int(input("Enter your age : "))
height = input("Enter your height : ")
print("Your name is:" + name , surname + " ", "You were born in:" + country_born + " " , "You are :" + " " + str(age) + " Years Old" + "," "You are :" + " " + height + "cm.")